import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://uktvplay.co.uk/');
  await page.getByRole('button', { name: 'YES I ACCEPT' }).click();
  await page.getByRole('button', { name: 'Channels' }).click();
  await page.getByRole('link', { name: 'Dave channel' }).click();
  await page.getByRole('link', { name: 'Drama channel' }).click();
  await page.getByRole('button', { name: 'Channels' }).click();
  await page.getByRole('link', { name: 'W channel' }).click();
  await page.getByRole('link', { name: 'Yesterday channel' }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'Comedy', exact: true }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'Drama', exact: true }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'Entertainment', exact: true }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'Documentaries' }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'Engineering', exact: true }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'Crime Drama' }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'Soaps' }).click();
  await page.getByRole('button', { name: 'Categories' }).click();
  await page.getByRole('link', { name: 'All Categories' }).click();
  await page.getByRole('link', { name: 'Atlantic Crossing,. Category: Period Drama. Description: Norwegian Crown Princess Martha fights to save her country during World War II.' }).click();
  await page.getByRole('link', { name: 'Atlantic Crossing', exact: true }).click();
  await page.getByRole('link', { name: 'SIGN IN' }).click();
  await page.getByPlaceholder('Email address').click();
  await page.getByPlaceholder('Email address').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Box Sets' }).click();
  await page.getByRole('link', { name: 'A to Z' }).click();
  await page.getByRole('button', { name: 'I', exact: true }).click();
  await page.getByRole('button', { name: 'K' }).click();
  await page.getByText('ABCDEFGHIJKLMNOPQRSTUVWXYZ0-9').click();
  await page.getByRole('button', { name: 'P' }).click();
  await page.getByRole('button', { name: 'S', exact: true }).click();
  await page.getByRole('button', { name: 'T', exact: true }).click();
  await page.getByRole('button', { name: 'N', exact: true }).click();
  await page.getByRole('button', { name: '0-9' }).click();
  await page.getByRole('button', { name: 'L', exact: true }).click();
  await page.getByRole('button', { name: 'K' }).click();
  await page.getByRole('button', { name: 'J' }).click();
  await page.getByRole('button', { name: 'I', exact: true }).click();
  await page.getByRole('button', { name: 'P' }).click();
  await page.getByRole('button', { name: 'O', exact: true }).click();
  await page.getByRole('button', { name: 'N', exact: true }).click();
  await page.getByRole('button', { name: 'M' }).click();
  await page.getByRole('button', { name: 'L', exact: true }).click();
  await page.getByRole('button', { name: 'K' }).click();
  await page.getByRole('button', { name: 'J' }).click();
  await page.getByRole('button', { name: 'I', exact: true }).click();
  await page.getByRole('button', { name: 'H', exact: true }).click();
  await page.getByRole('button', { name: 'G', exact: true }).click();
  await page.getByRole('button', { name: 'F' }).click();
  await page.getByRole('button', { name: 'E', exact: true }).click();
  await page.getByRole('button', { name: 'D', exact: true }).click();
  await page.getByRole('button', { name: 'C', exact: true }).click();
  await page.getByRole('button', { name: 'B', exact: true }).click();
  await page.getByRole('button', { name: 'A', exact: true }).click();
  await page.getByRole('button', { name: 'R', exact: true }).click();
  await page.getByRole('button', { name: 'S', exact: true }).click();
  await page.getByRole('button', { name: 'T', exact: true }).click();
  await page.getByRole('link', { name: 'A to Z' }).click();
  await page.getByRole('button', { name: 'P' }).click();
  await page.getByRole('link', { name: 'More' }).click();
  await page.getByRole('link', { name: 'Contact us', exact: true }).click();
  await page.locator('#tab-help').click();
  await page.locator('#tab-accessibility').click();
  await page.getByRole('link', { name: 'Set PIN' }).click();
  await page.locator('#tab-ways-to-watch').click();
  await page.getByRole('link', { name: 'What is UKTV Play?' }).click();
  await page.getByTitle('My List Button').click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.getByRole('link', { name: 'Home button' }).click();
});